site_name: Phage School 2025
theme:
  name: material
  favicon: favicon.ico  # ← Add this line

plugins:
  - search
  - mkdocs-jupyter


extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


extra_css:
  - css/arithmatex.css


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - codehilite
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Eco-Evo Principles Day 1:
      #- Python: day1_eco_evo_principles/python_notebook_day1.ipynb
      - Python: day1_eco_evo_principles/python_exercises_day1.ipynb
      #- R: day1/r.ipynb
      # - MATLAB - Static: day1_eco_evo_principles/html/matlab_exercises_day1.html
      - MATLAB - Exercises: day1_eco_evo_principles/matlab_solutions.md
  #- Day 2:
   #   - Python: day2/python.ipynb
   #   - R: day2/r.ipynb
   #   - MATLAB: day2/matlab.md
  #- Day 3:
      # - ...
 # - Day 4:
      # - ...